WPEFRAMEWORK_SNAPSHOT_VERSION = a705baa0ceeb7819f043cd763e0c36bdc60b8f70
WPEFRAMEWORK_SNAPSHOT_SITE_METHOD = git
WPEFRAMEWORK_SNAPSHOT_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_SNAPSHOT_INSTALL_STAGING = YES
WPEFRAMEWORK_SNAPSHOT_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

