WPEFRAMEWORK_MONITOR_VERSION = ca6d59902a9983ed88c7bce794087adfe8811832
WPEFRAMEWORK_MONITOR_SITE_METHOD = git
WPEFRAMEWORK_MONITOR_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_MONITOR_INSTALL_STAGING = YES
WPEFRAMEWORK_MONITOR_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

