WPEFRAMEWORK_WEBKITBROWSER_VERSION = 23a285a5d645d1c4e80c5b04b8a22dca28789e6e
WPEFRAMEWORK_WEBKITBROWSER_SITE_METHOD = git
WPEFRAMEWORK_WEBKITBROWSER_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_WEBKITBROWSER_INSTALL_STAGING = YES
WPEFRAMEWORK_WEBKITBROWSER_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

