WPEFRAMEWORK_DEVICEINFO_VERSION = 1e9c40d2641939d7a057dc88a9ddafe72d44b072
WPEFRAMEWORK_DEVICEINFO_SITE_METHOD = git
WPEFRAMEWORK_DEVICEINFO_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_DEVICEINFO_INSTALL_STAGING = YES
WPEFRAMEWORK_DEVICEINFO_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

