WPEFRAMEWORK_REMOTECONTROL_VERSION = c6600a7d6ac2c9027eefd6687bc17486688ec16a
WPEFRAMEWORK_REMOTECONTROL_SITE_METHOD = git
WPEFRAMEWORK_REMOTECONTROL_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_REMOTECONTROL_INSTALL_STAGING = YES
WPEFRAMEWORK_REMOTECONTROL_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

