WPEFRAMEWORK_PROVISIONING_VERSION = a64e95dca4e71e7f7fc3f134dbaf000e8d6f1ebd
WPEFRAMEWORK_PROVISIONING_SITE_METHOD = git
WPEFRAMEWORK_PROVISIONING_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_PROVISIONING_INSTALL_STAGING = YES
WPEFRAMEWORK_PROVISIONING_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

