WPEFRAMEWORK_VERSION = 0774c49b5cd1cbaf0e380953841b206217d823df
WPEFRAMEWORK_SITE_METHOD = git
WPEFRAMEWORK_SITE = git@github.com:Metrological/cppsdk.git
WPEFRAMEWORK_INSTALL_STAGING = YES
WPEFRAMEWORK_DEPENDENCIES = zlib

WPEFRAMEWORK_CONF_OPTS += -DINSTALL_HEADERS_TO_TARGET=ON -DCPPSDK_RPC=ON -DCPPSDK_PROCESS=ON

$(eval $(cmake-package))


