deps_config := \
	target/device/Config.in.linux.patches \
	target/linux/Config.in.versions \
	target/linux/Config.in.advanced \
	target/linux/Config.in \
	target/device/Config.in.u-boot \
	target/u-boot/Config.in \
	target/x86/syslinux/Config.in \
	target/x86/grub/Config.in \
	target/ramdisk/Config.in \
	target/romfs/Config.in \
	target/initramfs/Config.in \
	target/iso9660/Config.in \
	target/cpio/Config.in \
	target/tar/Config.in \
	target/squashfs/Config.in \
	target/jffs2/Config.in \
	target/ext2/Config.in \
	target/cloop/Config.in \
	target/cramfs/Config.in \
	target/Config.in \
	package/watchdog/Config.in \
	package/vidsink/Config.in \
	package/vidrend/Config.in \
	package/vidpproc_fw/Config.in \
	package/vidpproc/Config.in \
	package/video_ces/Config.in \
	package/videnc/Config.in \
	package/viddec_fw/Config.in \
	package/viddec/Config.in \
	package/tsout/Config.in \
	package/transcoder_server/Config.in \
	package/transcoder_pipeline/Config.in \
	package/transcoder_device/Config.in \
	package/transcoder_common/Config.in \
	package/thermal/Config.in \
	package/targetFS/Config.in \
	package/system_utils/Config.in \
	package/sven/Config.in \
	package/soc_audio/Config.in \
	package/smd_tools/Config.in \
	package/smd_sample_apps/Config.in \
	package/SMD_Common/Config.in \
	package/smd_avcap_shim/Config.in \
	package/sec_fw/Config.in \
	package/sec_diagnose/Config.in \
	package/sec/Config.in \
	package/remux/Config.in \
	package/pwm/Config.in \
	package/punit_fw_upgrade/Config.in \
	package/platform_config/Config.in \
	package/pic24_uart_drv/Config.in \
	package/pic24_uart/Config.in \
	package/pic24/Config.in \
	package/performancetools/Config.in \
	package/pal/Config.in \
	package/osal/Config.in \
	package/nsprpub_mw_dep/Config.in \
	package/nand_config/Config.in \
	package/mux/Config.in \
	package/mspod/Config.in \
	package/mfhlib/Config.in \
	package/keyrefresh/Config.in \
	package/itstore/Config.in \
	package/iosf/Config.in \
	package/intel_ce_pm/Config.in \
	package/init_man/Config.in \
	package/idts_security/Config.in \
	package/idts_media/Config.in \
	package/idts_core/Config.in \
	package/idts_common/Config.in \
	package/idtsal/Config.in \
	package/idl/Config.in \
	package/htuple/Config.in \
	package/hdmi_hdcp/Config.in \
	package/gsven/Config.in \
	package/graphics/Config.in \
	package/graphics_apps/Config.in \
	package/graphics_2d/Config.in \
	package/gpio/Config.in \
	package/generic_timer/Config.in \
	package/fw_load/Config.in \
	package/flashtool/Config.in \
	package/flash_encryption_signing_tools/Config.in \
	package/flash_appdata/Config.in \
	package/expbus/Config.in \
	package/edl/Config.in \
	package/display/Config.in \
	package/devmem/Config.in \
	package/demux/Config.in \
	package/cosai/Config.in \
	package/core/Config.in \
	package/config_database/Config.in \
	package/common/Config.in \
	package/clock_recovery/Config.in \
	package/clock_control/Config.in \
	package/clock/Config.in \
	package/cefdk/Config.in \
	package/bufmon/Config.in \
	package/avcap_samples/Config.in \
	package/avcap/Config.in \
	package/auto_eas/Config.in \
	package/audio/Config.in \
	package/api/Config.in \
	package/alsa_shim/Config.in \
	package/8051_SDK/Config.in \
	package/Config.IntelCE.in \
	package/fakeroot/Config.in \
	package/sed/Config.in \
	package/Config.in \
	toolchain/external-toolchain/Config.in.2 \
	toolchain/sstrip/Config.in \
	toolchain/mklibs/Config.in \
	toolchain/Config.in.2 \
	toolchain/external-toolchain/Config.in \
	toolchain/ccache/Config.in \
	toolchain/gcc/Config.in \
	toolchain/binutils/Config.in \
	toolchain/uClibc/Config.in \
	toolchain/kernel-headers/Config.in \
	toolchain/Config.in.1 \
	target/device/Config.in.toolchain \
	toolchain/Config.in \
	package/gnuconfig/Config.in \
	target/device/Config.in.mirrors \
	project/Config.in \
	target/device/Config.in \
	target/Config.in.arch \
	Config.in

$(BR2_DEPENDS_DIR)/config/auto.conf: \
	$(deps_config)

$(deps_config): ;
