WPEFRAMEWORK_WEBPROXY_VERSION = 97c8d86d750d1dcf1be9943b0a64cf26ad77ea61
WPEFRAMEWORK_WEBPROXY_SITE_METHOD = git
WPEFRAMEWORK_WEBPROXY_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_WEBPROXY_INSTALL_STAGING = YES
WPEFRAMEWORK_WEBPROXY_DEPENDENCIES = WPEFramework

#WPEFRAMEWORK_CONF_OPTS += -DINSTALL_HEADERS_TO_TARGET=ON -DCPPSDK_RPC=ON -DCPPSDK_PROCESS=ON

$(eval $(cmake-package))

