WPEFRAMEWORK_DIALSERVER_VERSION = da957434365868be3c5eb2a12782d0a0e13b69b8
WPEFRAMEWORK_DIALSERVER_SITE_METHOD = git
WPEFRAMEWORK_DIALSERVER_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_DIALSERVER_INSTALL_STAGING = YES
WPEFRAMEWORK_DIALSERVER_DEPENDENCIES = WPEFramework

$(eval $(cmake-package))

